### ISSUE TITLE
depth should not default to infinity

### ISSUE THREAD

**Issue by jimmywarting** [jfhbrook/node-flatten#8]
Would like to use node-flatten as a polyfill for `Array.prototype.flat` (more or less). But your are not spec compatible with the depth argument, the default should not be Infinity

```js
module.exports = Array.prototype.flat 
  ? (arr, depth) => arr.flat(depth) 
  : (arr, depth) => { /* code */ }
```

**Comment by jfhbrook** [comment]
This isn't a polyfill, just a utility I hacked up a bunch of years ago. This implementation probably isn't even performant!

You should look elsewhere, I'm not interested in working on this project.
